### PR TITLE
Travis-CI

### PR DESCRIPTION
**Pull request by ocefpaf**
Simple `.travis.yml` config.

Ping @lukecampbell

### CODE REVIEW

**Comment by lukecampbell** [comment]
Even though it's failing, I'm going to merge. Due to the recent changes in the main compliance checker, I need to create a release and then update the requirements for this plugin.

**Comment by ocefpaf** [comment]
OK.  I am working on this and I will send a new PR soon.

**Comment by lukecampbell** [comment]
I'll be trying to push a CC release today; once that's done the tests will pass for this. We removed a bunch of dependencies and https://github.com/ioos/cc-plugin-glider/pull/4 introduces changes that won't pass any automated testing until we point to the latest changes in compliance checker.

**Comment by daf** [comment]
@lukecampbell 2.1?

**Comment by lukecampbell** [comment]
2.0.1

**Comment by lukecampbell** [comment]
2.1 is laid out in a roadmap:
https://github.com/ioos/compliance-checker/issues?q=is%3Aopen+is%3Aissue+milestone%3A%22Version+2.1%22

**Comment by lukecampbell** [comment]
The problem I have is that, from a purely version semantics point of view, what we have right now is not backwards compatible to 2.0... which should mean 2.1 not 2.0.1... Let me talk to the IOOS folks and ask if they're cool with us going with 2.1 now with these changes which are, in my opinion, big:

 - Python 3 support
 - Major bugs have been addressed
 - Formatting changes and better descriptions for CF
 - Removal of deprecated dependencies

**Comment by ocefpaf** [comment]
> Python 3 support

Working on that (together with my next Travis-CI PR).

**Comment by daf** [comment]
Yeah, and rename what's currently the "2.1" milestone as something else.

**Pull request merged**
