### PR TITLE
Python 3

### PR DESCRIPTION
**Pull request by ocefpaf**
In this PR:

- python 2 and 3 codebase
- flake8 test
- pep8
- clean `MANIFEST.in`

The Python 3 tests needs a new release of compliance-checker to run.

### CODE REVIEW

**Comment by lukecampbell** [comment]
Oh wow, thank you!

**Comment by ocefpaf** [comment]
Ping!

**Comment by lukecampbell** [comment]
Pong!

**Comment by ocefpaf** [comment]
New release :wink:

**Comment by lukecampbell** [comment]
aw crap you bring up a good point, I never considered how to deal with releases with regards to plugins. @daf any ideas on how we should deal with this?

**Comment by daf** [comment]
Well it's just an independent python package, so normal distribution methods?  Bump version, upload to PyPI, conda packaging...

**Pull request merged**
